In [3]:
import pandas as pd

In [7]:
df = pd.DataFrame({
    "country" : ["USA","USA","INDIA","INDIA"],
    "year" : [2020,2021,2020,2021],
    "sales" : [100,120,90,110],
    "profile": [20,25,18,22]
})
df

  country  year  sales  profile
0     USA  2020    100       20
1     USA  2021    120       25
2   INDIA  2020     90       18
3   INDIA  2021    110       22

In [13]:
# Melt function use to reshaping the data
# Melt help to convert wide data to long formate (means horitonal to vertical)
# syntax melt(id_vars, value_vars, var_name, var_value)
melted_df = df.melt(
    id_vars = ["country", "year"],  #ye column change nhi honge
    value_vars = ["sales", "profile"], #ye column ko melt karna hai 
    var_name = "metric",  #new_column name
    value_name = "value"   #new_column value name
)

In [14]:
# Pivot use for reverse of melt long formate to wide 
melted_df.pivot(
    index = ["country", "year"], #index must be unqiue value so we use country and year pair to make new 
    columns= "metric", #hum metric se column create karege 
    values= "value",  #her ek column ki value value denge
)

metric        profile  sales
country year
INDIA   2020       18     90
        2021       22    110
USA     2020       20    100
        2021       25    120