In [4]:
import pandas as pd

In [16]:
# DataFrame
# Creation
# 1. dictionary of list
info = {
    "Name" : ["piyush", "Shree", "Om"],
    "CGPA" : [9.3, 9.8, 7.6],
    "Age" : [22,21,26]
}

df = pd.DataFrame(info)
print(df, type(df))
print(df.index)
print(df.columns)

     Name  CGPA  Age
0  piyush   9.3   22
1   Shree   9.8   21
2      Om   7.6   26 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'CGPA', 'Age'], dtype='object')

In [21]:
# 2. list of list
import numpy as np
np_arr = np.array([["adam",23],["bob",25],["piyush", 24]])
df = pd.DataFrame(np_arr, columns = ["Name","Age"])
df

     Name Age
0    adam  23
1     bob  25
2  piyush  24

In [25]:
# Read JSON
df = pd.read_json("4_employee_data.json")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [26]:
# Read CSV
df = pd.read_csv("4_employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [41]:
# DataFrame Methods -> Helps in EDA
df.head() #by default string 5 rows
df.head(2)

df.tail() # last 5rows

df.sample() #random single row
df.sample(5) #random 5rows

# df.info() #information of dtype , store

df.shape # give tuple (row,column)

df.describe() #give min, max , std (only for numerical rows)

df.columns

df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [29]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000