In [16]:
import pandas as pd
df = pd.read_csv("6.1_raw_data.csv")

In [20]:
# Data Cleaning
# 1.handle missing values
df.isnull()  # show true if NaN present(Not a Number)
df.isnull().sum()


df.dropna() #give only those row which have no NaN
# df.dropna(axis = 1) #give columns

df.fillna(0)
cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)
cleaned_data

df.ffill() #forward fill top value niche copy ho jayegi NAN me 
df.bfill() #backward fill from bottom to top fill

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [27]:
# 2. Handle Duplicates

df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()

df.drop_duplicates()
df.drop_duplicates(inplace = True) #original dataset me change ho jayega

In [28]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [39]:
# 3. Handle Datatypes & Datetime

# change datatypes using astype function
df.dtypes
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

# to_datetime() function
date_str = pd.Series(pd.to_datetime("26-12-30"))
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [51]:
# 4. Handle String
df["gender"].str.capitalize()
df["gender"].str.upper()
df["name"].str.split(" ")
df["country"].str.contains('india', case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [44]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0