In [72]:
import pandas as pd

In [73]:
df = pd.read_csv("6.1_raw_data.csv")

## Feature Engineering
- ### It means tranforming the data to create some new column or new feature that improve the performance of the model.

In [74]:
# 1. apply()
# apply() function which take function as parameter
# this function is called high order function it means
# it take function as parameter and can return the function
# example : add a new column for tax 20% or income > 50k and 10% below that.
df2 = df.copy()

# hum df2 ke under tax columns create karege = df2 ke income ke uper ek function apply karenge 
df2["tax"] = df2["income"].apply(lambda x : "20%" if x > 50000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [75]:
# 2. map()
# map() -> existing value ko map karna cahate hai 
gender_map = {"Male":"M", "Female" : "F", "Unknown": "U"} 
df2["gender"] = df2["gender"].map(gender_map)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [76]:
# 3. assign() function -> important in sytax
# assign a new column
# create a new_income and having 10% increment
df2 = df2.assign(new_income = df2["income"] * 1.1)
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [77]:
 # 4. replace(old,new)
df2["country"] = df2["country"].replace("USA","United State")
df2

    id          name   age       country gender   income  tax  new_income
0    1      John Doe  29.0  United State      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN        Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0         China      M  51000.0  20%     56100.0
6    6           NaN  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State    NaN  58000.0  20%     63800.0

In [102]:
# rename Columns & row
df2.columns
# Capitalize the columns name
df2.columns = ["Id","Name","Age","Country","Gender","Income", "Tax","New_Income"]
df2.rename(columns={"Income":"Salary"})
df2.rename(index = {1 : "First"})


# Sorting
df2.sort_values("Income") #asending order 
df2.sort_values(["Income"], ascending=False) #descending order 
# if income se then sort using age
df2 = df2.fillna(50)
sorted_df = df2.sort_values(["Income","Age"])  # se the (10,8) label

sorted_df.sort_index()

# Reset Index
sorted_df.reset_index()  # preserved the original index
sorted_df.reset_index(drop=True) # remove old index

# Ranking
sorted_df["Ranking"] = sorted_df["Income"].rank()
# tie hogaye gi toh average aayega
# do we want dense number means integer
sorted_df["Ranking"] = sorted_df["Income"].rank(method="dense")
# sorted_df["Ranking"] = sorted_df["Income"].rank(method="min")
# sorted_df["Ranking"] = sorted_df["Income"].rank(method="max")
sorted_df


# rearrange the columns
# tax column will come on last
sorted_df[["Id", "Name" , "Age", "Country" , "Gender" , "Income", "New_Income", "Ranking", "Tax"]]

,Id,Name,Age,Country,Gender,Income,New_Income,Ranking,Tax
4,4,Maria Garcia,34.0,Spain,F,50.0,50.0,1.0,10%
9,9,Carlos Ruiz,50.0,Mexico,M,45000.0,49500.0,2.0,10%
3,3,Alex,50.0,United State,U,47000.0,51700.0,3.0,10%
5,5,Li Wei,27.0,China,M,51000.0,56100.0,4.0,20%
0,1,John Doe,29.0,United State,M,55000.0,60500.0,5.0,20%
1,1,John Doe,29.0,United State,M,55000.0,60500.0,5.0,20%
10,10,Emily Davis,31.0,United State,50,58000.0,63800.0,6.0,20%
8,8,Rachel Lee,29.0,United State,F,62000.0,68200.0,7.0,20%
2,2,Jane Smith,50.0,Canada,F,62000.0,68200.0,7.0,20%
7,7,Ahmed Khan,38.0,50,M,68000.0,74800.0,8.0,20%
6,6,50,45.0,India,F,73000.0,80300.0,9.0,20%

In [87]:
df2

    Id          Name   Age       Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0  United State      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  20%     60500.0
2    2    Jane Smith  50.0        Canada      F  62000.0  20%     68200.0
3    3          Alex  50.0  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F     50.0  10%        50.0
5    5        Li Wei  27.0         China      M  51000.0  20%     56100.0
6    6            50  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            50      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  50.0        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State     50  58000.0  20%     63800.0

In [156]:
# Practics Task -> Id columns add to last 
df3 = df2.copy()

new_col_order = [x for x in df3.columns if x != "Id"]
new_col_order.append("Id")
df3 = df3[new_col_order]
df3

            Name   Age       Country Gender   Income  Tax  New_Income  Id
0       John Doe  29.0  United State      M  55000.0  20%     60500.0   1
1       John Doe  29.0  United State      M  55000.0  20%     60500.0   1
2     Jane Smith  50.0        Canada      F  62000.0  20%     68200.0   2
3           Alex  50.0  United State      U  47000.0  10%     51700.0   3
4   Maria Garcia  34.0         Spain      F     50.0  10%        50.0   4
5         Li Wei  27.0         China      M  51000.0  20%     56100.0   5
6             50  45.0         India      F  73000.0  20%     80300.0   6
7     Ahmed Khan  38.0            50      M  68000.0  20%     74800.0   7
8     Rachel Lee  29.0  United State      F  62000.0  20%     68200.0   8
9    Carlos Ruiz  50.0        Mexico      M  45000.0  10%     49500.0   9
10   Emily Davis  31.0  United State     50  58000.0  20%     63800.0  10

In [135]:
df2

    Id          Name   Age       Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0  United State      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  20%     60500.0
2    2    Jane Smith  50.0        Canada      F  62000.0  20%     68200.0
3    3          Alex  50.0  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F     50.0  10%        50.0
5    5        Li Wei  27.0         China      M  51000.0  20%     56100.0
6    6            50  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            50      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  50.0        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State     50  58000.0  20%     63800.0